SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME ='habitacionID'
AND 	TABLE_SCHEMA='bd_dulces';

SELECT NOW() FechaHoraActual, DAY(NOW()) AS SoloDia;
SELECT DATEDIFF(DATE(NOW()),'2024-03-18') AS DiferenciaEnDias;

SELECT DATE_ADD(DATE(NOW()), INTERVAL 1 YEAR) AS En_1_Anio;
SELECT DATE_ADD(DATE(NOW()), INTERVAL 3 MONTH) AS En_3_Meses;
SELECT DATE_ADD(DATE(NOW()), INTERVAL 15 DAY) AS En_15_Dias;